package dev.dietermai.coreutil.cli.cat.error;

public enum ExitCode {
	SUCCESS,
	AMBIGUOUS_OPTIONS,
	UNRECOGNIZED_OPTION,
	MISSING_OPTION,
	MISSING_ARGUMENT,
	ALREADY_SELECTED_OPTION,
	PARSER_ERROR,
	UNEXPECTED_PARSING_ERROR,
	OTHER_ERROR, 
	MISSNG_EXCEPTION,
	FILE_NOT_FOUND,
	FILE_CLOSE_ERROR;
	;

	public int value() {
		return ordinal();
	}
}
